apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: {{ template "chart.chart" . }}
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ template "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  minReplicas: {{ .Values.hpa.replicas.min }}
  maxReplicas: {{ .Values.hpa.replicas.max }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "chart.chart" . }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.cpu.utilization }}