apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.chart" . }}
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ template "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ template "chart.name" . }}
    release: {{ .Release.Name }}
